name: sbakusara_presence_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter
  get: 4.6.5
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0
  dio: ^5.2.1+1
  flutter_slidable: ^3.0.0
  iconify_flutter: ^0.0.5
  google_nav_bar: ^5.0.6
  intl: ^0.18.1
  image_picker: ^1.0.1
  geolocator: ^9.0.2
  permission_handler: ^10.4.3
  app_settings: ^5.0.0
  map_launcher: ^2.5.0+1
  geocoding: ^2.1.0
  flutter_swipe_action_cell: ^3.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon_launcher.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon_launcher.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon_launcher.png"
