name: sbakusara_presence_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter
  get: 4.6.5
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0
  dio: ^5.2.1+1
  flutter_slidable: ^3.0.0
  iconify_flutter: ^0.0.5
  google_nav_bar: ^5.0.6
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true
